---
title: "DV (5) HW"
author: Carter Wyatt
format: html
editor: visual
embed resources: true
---

```{r}
library(tidyverse)
# Read in the data 
wncaa <- read_csv("https://raw.githubusercontent.com/vaiseys/dav-course/main/Data/wncaa.csv")

# Glimpse the data 
glimpse(wncaa)
```

## Question 1

```{r}
wncaa |>
  filter(tourney_finish == "Champ") |>
  group_by(school) |>
summarise(number = n()) |>
  mutate(freq = number / sum(number), pct = round((freq*100), 0), 0) |>
  ggplot(aes(x = school, fill = pct)) +
  geom_bar() +
  coord_flip()
                    
  
```

What patterns do you see?

I see that a large majority of the schools are in between the 10 and 20 mark.

Who are the two teams that have won the most?

Tennessee and Uconn have won the most by far.

## Question 2

```{r}

champs <- wncaa |>
  filter(tourney_finish == "Champ")

champ_names <- unique(champs$school)
```

```{r}
winners <- wncaa %>% 
  filter(school %in% champ_names)
```

```{r}
  ggplot(data = winners, 
         aes(x = school, y = seed)) +
    geom_boxplot() + coord_flip() + geom_jitter() + geom_jitter(position = position_jitter(width = 5))
```

## Question 3

## Question 4
