---
title: "MD HW5"
author: "Carter Wyatt"
format: html
editor: visual
embed resources: true
---

```{r}
library(tidyverse)

twitch_data <- read_csv("https://raw.githubusercontent.com/vaiseys/dav-course/main/Data/twitchdata-update.csv")
```

```{r}
library(janitor)
twitch_data <- clean_names(twitch_data)

# Inspect new names
colnames(twitch_data)
```

## Question 1

```{r}

twitch_data |>
  select(channel, average_viewers, followers) |>
  sample_n(size = 5) 

```

What do you notice?

```{r}
twitch_data |>
  select(channel, average_viewers, followers) |>
  sample_n(size = 5) |>
summarise(average_viewers, followers)
```

Describe the results in a few words. Does anything capture your attention?

```{r}
twitch_data |>
  select(channel, average_viewers, followers) |>
  sample_n(size = 5) |>
summarise(average_viewers, followers) |>
  ggplot(
    aes(x = average_viewers, y = followers)
  ) +
  geom_point() +
  labs(x = "Average Viewers", y = "Followers", title = "Random Channels")
```

What do you notice?

```{r}
twitch_data |>
  select(channel, average_viewers, followers) |>
  sample_n(size = 5) |>
summarise(average_viewers, followers) |>
  ggplot(
    aes(x = average_viewers, y = followers)
  ) +
  geom_point() +
  labs(x = "Average Viewers", y = "Followers", title = "Random Channels") +
  scale_x_log10() + scale_y_log10()
```

What do you see now? How does the relationship look like?

```{r}
twitch_data <- twitch_data %>% 
  mutate(log_viewers = log10(average_viewers), 
         log_followers = log10(followers))
```

## Question 2

```{r}
fit1 <- lm(log_viewers ~ average_viewers,  data = twitch_data)
```

## Question 3

```{r}
library(broom)

pred_data <- augment(fit1)

# glimpse our new data 
glimpse(pred_data)
```

\$\$ 1.1\^{0.4} = 4.442731 \$\$

A 10% increase in followers is associated with a 4.2% increase in the average number of viewers.

## Question 4

## Question 5

## Question 6
