---
title: "project_final"
author: Carter Wyatt
format: html
editor: visual
embed-resources: true
echo: false
---

```{r}
library(tidyverse)
library(tidymodels)
library(dplyr)
```

```{r}
NBA_Stats <- read_delim("2023-2024 NBA Player Stats - Regular.csv",
           delim = ";")
glimpse(NBA_Stats)

NBA_Stats <- NBA_Stats |>
  select(PTS, AST, TRB, MP, Player)


NBA_MVPs <- NBA_Stats |>
  mutate(
    is_MVP = as.factor(ifelse(
      Player %in% c("Joel Embiid", "Nikola Jokic", "Giannis Antetokounmpo", "James Harden", "Russell Westbrook", "Stephen Curry", "Kevin Durant", "LeBron James"), 1, 0))
  )




```

```{r}
NBA_MVPs |>
  ggplot(
    aes(x = PTS)
  ) + geom_histogram()
```

```{r}

NBA_MVPs |>
  ggplot(
    aes(x = PTS, y = MP)
  ) + geom_point() +
  geom_smooth(method = lm, se = FALSE)
  

```

```{r}
NBA_MVPs |>
  ggplot(
    aes(x = PTS)
  ) + geom_boxplot()
```

```{r}
MVP_Fit <- logistic_reg() |>
  set_engine("glm") |>
  fit(is_MVP ~ PTS + AST + TRB + MP, data = NBA_MVPs, family = "binomial")

tidy(MVP_Fit) 
```

$$
\widehat{is\_MVP} = -8.51 + 0.14*PTS + 0.04*AST + 0.22TRB + 0.30*FG 
$$

```{r}
tidy(MVP_Fit, conf.int = TRUE) 
```

```{r}
df_MVP <- augment(MVP_Fit$fit)

df_MVP |>
  ggplot(aes(x = .resid)) +
  geom_histogram()
```

```{r}
df_MVP |>
  ggplot(
    aes(y = .resid, x = PTS)) +
  geom_point()
```

```{r}
df_MVP |>
  ggplot(aes(y = .resid, x = .fitted)) +
  geom_point()
```

Last graph: fan out = not constant variance --\> systematic patterns

```{r}
player <- tibble(
  PTS = 20,
  AST = 5, 
  TRB = 5, 
  MP = 5
)

predict(MVP_Fit, player)
```

need a log

histogram or plot

(give context)

Citations are not needed unless you used another one

```{r}
NBA_Stats |> 
select(PTS, AST, TRB, MP) |>
  cor()
```
